'use client';

import { useState } from 'react';
import { AppLayout } from '@/components/layout/app-layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { DocumentTextIcon, CheckIcon } from '@heroicons/react/24/outline';

export default function Submit() {
  const [formData, setFormData] = useState({
    assignmentTitle: '',
    studentName: '',
    studentId: '',
    submissionNotes: '',
  });
  const [isSubmitted, setIsSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // TODO: Implement actual submission logic
    setIsSubmitted(true);
    setTimeout(() => setIsSubmitted(false), 3000);
  };

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const assignmentTemplate = `# Chatbot Assessment Assignment

## Assignment Details
- **Title**: ${formData.assignmentTitle || '[Assignment Title]'}
- **Student**: ${formData.studentName || '[Student Name]'}
- **ID**: ${formData.studentId || '[Student ID]'}
- **Date**: ${new Date().toLocaleDateString()}

## Objective
Evaluate the performance and capabilities of the AI chatbot through structured conversations and analysis.

## Tasks
1. **Conversation Quality Assessment**
   - Initiate conversations on various topics
   - Evaluate response relevance and accuracy
   - Test context understanding capabilities

2. **Technical Evaluation**
   - Test response time and system performance
   - Evaluate user interface and experience
   - Document any technical issues encountered

3. **Analysis and Documentation**
   - Document conversation examples
   - Provide ratings on different criteria
   - Submit detailed feedback and recommendations

## Submission Requirements
- Complete all required conversations
- Provide detailed analysis and ratings
- Include screenshots or examples where relevant
- Submit within the specified deadline

## Additional Notes
${formData.submissionNotes || '[Add any additional notes or comments here]'}

---
*This template was generated by the Chatbot Assessment platform.*`;

  return (
    <AppLayout>
      <div className="h-full overflow-y-auto">
        <div className="max-w-4xl mx-auto p-8">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground">Submit Assignment</h1>
            <p className="text-foreground-muted mt-1">
              Generate and submit your chatbot assessment assignment
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Form Section */}
            <div className="glass rounded-xl p-6">
              <div className="flex items-center space-x-3 mb-6">
                <DocumentTextIcon className="w-6 h-6 text-accent" />
                <h2 className="text-xl font-semibold text-foreground">Assignment Information</h2>
              </div>

              <form onSubmit={handleSubmit} className="space-y-4">
                <Input
                  label="Assignment Title"
                  placeholder="Enter assignment title"
                  value={formData.assignmentTitle}
                  onChange={(e) => handleInputChange('assignmentTitle', e.target.value)}
                  required
                />

                <Input
                  label="Student Name"
                  placeholder="Enter your full name"
                  value={formData.studentName}
                  onChange={(e) => handleInputChange('studentName', e.target.value)}
                  required
                />

                <Input
                  label="Student ID"
                  placeholder="Enter your student ID"
                  value={formData.studentId}
                  onChange={(e) => handleInputChange('studentId', e.target.value)}
                  required
                />

                <div className="space-y-2">
                  <label className="block text-sm font-medium text-foreground">
                    Additional Notes
                  </label>
                  <textarea
                    placeholder="Enter any additional notes or requirements"
                    value={formData.submissionNotes}
                    onChange={(e) => handleInputChange('submissionNotes', e.target.value)}
                    rows={4}
                    className="w-full px-4 py-3 bg-surface border border-border rounded-lg text-foreground placeholder:text-foreground-subtle focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent transition-all duration-200"
                  />
                </div>

                <Button 
                  type="submit" 
                  variant="primary" 
                  className="w-full"
                  disabled={isSubmitted}
                >
                  {isSubmitted ? (
                    <div className="flex items-center space-x-2">
                      <CheckIcon className="w-5 h-5" />
                      <span>Submitted Successfully!</span>
                    </div>
                  ) : (
                    <div className="flex items-center space-x-2">
                      <DocumentTextIcon className="w-5 h-5" />
                      <span>Generate Assignment</span>
                    </div>
                  )}
                </Button>
              </form>
            </div>

            {/* Template Preview Section */}
            <div className="glass rounded-xl p-6">
              <h2 className="text-xl font-semibold text-foreground mb-6">Assignment Template Preview</h2>
              
              <div className="bg-surface rounded-lg p-4 max-h-96 overflow-y-auto">
                <pre className="text-sm text-foreground-muted whitespace-pre-wrap font-mono leading-relaxed">
                  {assignmentTemplate}
                </pre>
              </div>

              <div className="mt-4 flex gap-3">
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => {
                    navigator.clipboard.writeText(assignmentTemplate);
                  }}
                >
                  Copy Template
                </Button>
                
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => {
                    const blob = new Blob([assignmentTemplate], { type: 'text/markdown' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `chatbot-assessment-${formData.studentId || 'template'}.md`;
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                >
                  Download
                </Button>
              </div>
            </div>
          </div>

          {/* Instructions */}
          <div className="mt-8 glass rounded-xl p-6">
            <h2 className="text-xl font-semibold text-foreground mb-4">Instructions</h2>
            <div className="prose prose-invert max-w-none">
              <ol className="text-foreground-muted space-y-2">
                <li>Fill in the assignment information form with your details</li>
                <li>Review the generated template in the preview section</li>
                <li>Click &quot;Generate Assignment&quot; to create your submission template</li>
                <li>Copy the template or download it as a markdown file</li>
                <li>Complete the assessment tasks using the chatbot interface</li>
                <li>Fill in your findings and submit according to your course requirements</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}